package asgn2GUI;

import java.awt.BorderLayout;
import java.awt.Frame;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import asgn2Exceptions.TrainException;
import asgn2RollingStock.FreightCar;
import asgn2RollingStock.Locomotive;
import asgn2RollingStock.PassengerCar;
import asgn2RollingStock.RollingStock;
import asgn2Train.DepartingTrain;

/**
 * Graphical user interface to arrange all panels related to departing train
 * configuration.
 * 
 * This JFrame is also a action listener handling all events generated by
 * panels.
 * 
 * @author  Charleston Telles(n8388342) (developer), 
 * 			Phurpa Wangchuk(n8448060) (reviewer)
 * 
 */
public class DepartingTrainFrame extends JFrame implements ActionListener {

	/**
	 * Mandatory class ID to be used by serialisation
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * Panel related to a departing Train canvas
	 */
	private AssembledTrainPanel assembledTrainPanel;
	/**
	 * Panel related to passenger car configuration
	 */
	private PassengerCarPanel passengerCarPanel;
	/**
	 * Panel related to boarding passengers configuration
	 */
	private BoardingTrainPanel boardingTrainPanel;
	/**
	 * Panel related to locomotive configuration
	 */
	private LocomotivePanel locomotivePanel;
	/**
	 * Panel related to freight car configuration
	 */
	private FreightCarPanel freightCarPanel;

	/**
	 * The departing train being configured
	 */
	private DepartingTrain departingTrain;
	/**
	 * sum up gross weight for each rolling stock
	 */
	private List<Integer>grossWeightList; 

	/**
	 * Default Constructor
	 * 
	 * @param title
	 *            the application screen title
	 * 
	 * @throws HeadlessException
	 */
	public DepartingTrainFrame(String title) throws HeadlessException {
		super(title);
		initComponents();
		grossWeightList = new ArrayList<Integer>();
	}

	/**
	 * Sets the JFrame Layout and arrange the components in the screen
	 * 
	 */
	private void initComponents() {
		setExtendedState(Frame.MAXIMIZED_BOTH);
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setLayout(new BorderLayout());

		departingTrain = new DepartingTrain();

		assembledTrainPanel = new AssembledTrainPanel(departingTrain, this);
		passengerCarPanel = new PassengerCarPanel(this);
		boardingTrainPanel = new BoardingTrainPanel(this);
		locomotivePanel = new LocomotivePanel(this);
		freightCarPanel = new FreightCarPanel(this);

		this.getContentPane().add(assembledTrainPanel, BorderLayout.CENTER);
		this.getContentPane().add(passengerCarPanel, BorderLayout.SOUTH);
		this.getContentPane().add(boardingTrainPanel, BorderLayout.NORTH);
		this.getContentPane().add(locomotivePanel, BorderLayout.WEST);
		this.getContentPane().add(freightCarPanel, BorderLayout.EAST);
	}

	/**
	 * Handles all events created within the Departing Train application.
	 * 
	 * Also capture all exceptions eventually created by events and shows the
	 * messages to the user in a friendly way.
	 * 
	 */
	@Override
	public void actionPerformed(ActionEvent e) {
		try {

			if (((JButton) e.getSource()).getParent() instanceof LocomotivePanel) {
				handleLocomotivePanelEvents(e);
			} else if (((JButton) e.getSource()).getParent() instanceof PassengerCarPanel) {
				handlePassengerCarPanelEvents(e);
			} else if (((JButton) e.getSource()).getParent() instanceof FreightCarPanel) {
				handleFreightCarPanelEvents(e);
			} else if (((JButton) e.getSource()).getParent() instanceof BoardingTrainPanel) {
				handleBoardingTrainPanelEvents(e);
			}
			this.repaint(); // VERY IMPORTANT: IT REPAINTS THE WHOLE FRAME
			updateBoardingPanel();

		} catch (Exception ex) {
			JOptionPane.showMessageDialog(this, ex.getMessage(),
					"Train Configuration Error", JOptionPane.ERROR_MESSAGE);
		}
	}

	/**
	 * Handles a new locomotive creation event
	 * 
	 * @param e
	 *            actionEvent
	 * 
	 * @throws TrainException
	 */
	private void handleLocomotivePanelEvents(ActionEvent e)
			throws TrainException {
		LocomotivePanel panel = (LocomotivePanel) ((JButton) e.getSource())
				.getParent();
		int weight = panel.getWeight();
		int powerClass = panel.getPowerClass();
		String engineType = panel.getEngineType();
		departingTrain.addCarriage(new Locomotive(weight, powerClass
				+ engineType));
		grossWeightList.add(weight);
	}

	/**
	 * Handles a new passenger car creation event
	 * 
	 * @param e
	 *            actionEvent
	 * 
	 * @throws TrainException
	 */
	private void handlePassengerCarPanelEvents(ActionEvent e)
			throws TrainException {
		PassengerCarPanel panel = (PassengerCarPanel) ((JButton) e.getSource())
				.getParent();
		int weight = panel.getWeight();
		int numberOfSeats = panel.getNumberOfSeats();
		departingTrain.addCarriage(new PassengerCar(weight, numberOfSeats));
		grossWeightList.add(weight);
	}

	/**
	 * Handle a new freight car creation event
	 * 
	 * @param e
	 *            actionEvent
	 * 
	 * @throws TrainException
	 */
	private void handleFreightCarPanelEvents(ActionEvent e)
			throws TrainException {
		FreightCarPanel panel = (FreightCarPanel) ((JButton) e.getSource())
				.getParent();
		int weight = panel.getWeight();
		String goodsType = panel.getGoodsType();
		departingTrain.addCarriage(new FreightCar(weight, goodsType));
		grossWeightList.add(weight);
	}

	/**
	 * Handles events related to passenger boarding panel.
	 * 
	 * @param e
	 *            actionEvent
	 * 
	 * @throws TrainException
	 */
	private void handleBoardingTrainPanelEvents(ActionEvent e)
			throws TrainException {
		BoardingTrainPanel panel = (BoardingTrainPanel) ((JButton) e
				.getSource()).getParent();

		if (e.getActionCommand().equalsIgnoreCase("remove car")) {
			departingTrain.removeCarriage();
			grossWeightList.remove(grossWeightList.size()-1);
		} else if (e.getActionCommand().equalsIgnoreCase("board")) {
			panel.setPassengerOut(""
					+ departingTrain.board(panel.getNumberOfPassenger()));
		} else if (e.getActionCommand().equalsIgnoreCase("reset")) {
			resetTrain();
		}
	}

	/**
	 * Updates the information about the current departing train.
	 */
	private void updateBoardingPanel() {
		RollingStock locomotive = departingTrain.firstCarriage() instanceof Locomotive ? departingTrain
				.firstCarriage() : null;
		boardingTrainPanel.setTrainCanMove("" + departingTrain.trainCanMove());
		boardingTrainPanel.setLocomotiveCapacity(locomotive != null ? ""
				+ ((Locomotive) locomotive).power() : "0");
		boardingTrainPanel.setNumberOnBoard(departingTrain.numberOnBoard()
				+ "/" + departingTrain.numberOfSeats());
		boardingTrainPanel.setTotalWeight(""+getTotalGrossWeight());		
	}

	/**
	 * calculated the total gross weight
	 * 
	 * @return total gross weight
	 */
	private int getTotalGrossWeight(){
		int totalWeight = 0;
		for (Integer weight : grossWeightList)
			totalWeight += weight;
		return totalWeight;
	}
	
	/**
	 * reset the current Departing Train.
	 * Unboard every single passenger and remove all carriages.
	 * 
	 * @throws TrainException 
	 * 
	 */
	private void resetTrain() throws TrainException{
		int countCarriage = 0;
		RollingStock rs = departingTrain.firstCarriage();
		while(rs != null){
			countCarriage++;
			if (rs instanceof PassengerCar)
				((PassengerCar)rs).alight(((PassengerCar)rs).numberOnBoard());
			rs = departingTrain.nextCarriage();
		}		
		while (countCarriage-- > 0){
			departingTrain.removeCarriage();
		}
		grossWeightList = new ArrayList<Integer>();
		boardingTrainPanel.setPassengerOut("00");
	}
		
	/**
	 * Main method used to initialise a Departing Train application
	 * 
	 * @param args
	 */
	public static void main(String[] args) {
		DepartingTrainFrame departingTrainFrame = new DepartingTrainFrame(
				"Departing Train");

		departingTrainFrame.setVisible(true);
	}

}
